# Generated by Django 3.1.6 on 2021-02-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210213_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grassgraph',
            name='data',
            field=models.ImageField(upload_to='grass/'),
        ),
    ]
