# Generated by Django 3.2.6 on 2021-08-31 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_grassgraph_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('identifier', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('html', models.FileField(upload_to='html/')),
                ('navbar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.navbar', verbose_name='NavBar')),
            ],
        ),
    ]
