# Generated by Django 3.2.6 on 2021-08-31 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_navbar_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='navbar',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.navbar', verbose_name='NavBar'),
        ),
    ]
