# Generated by Django 3.2.6 on 2021-08-31 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_navbar_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticpage',
            old_name='hiddel',
            new_name='hidden',
        ),
    ]
