# Generated by Django 3.2.6 on 2021-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_hiddel_staticpage_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='html_safe_name',
            field=models.CharField(default='BAD', max_length=25),
            preserve_default=False,
        ),
    ]
