# Generated by Django 3.2.6 on 2021-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_staticpage_html_safe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='template',
            field=models.BooleanField(default=True),
        ),
    ]
