# Generated by Django 3.2.7 on 2021-09-04 19:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_staticpage_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('repository', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='project/')),
                ('featured', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='projects.ProjectTag')),
            ],
        ),
    ]
