# Generated by Django 3.2.7 on 2021-09-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_projecttag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='brief',
        ),
    ]
