# Generated by Django 3.2.7 on 2021-09-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_rename_description_project_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief',
            field=models.TextField(max_length=150),
        ),
    ]
