# Generated by Django 3.2.4 on 2021-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sending_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
