# Generated by Django 3.2.4 on 2021-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchat', '0002_alter_email_sending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='captcha_score',
            field=models.FloatField(null=True),
        ),
    ]
