# Generated by Django 3.2.6 on 2021-09-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailchat', '0003_alter_email_captcha_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='verified',
        ),
    ]
