# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Website

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest # Closest thing to Debian
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SECRET_KEY: GhubActionSecKey
        file_name: .env
    - name: Check
      run: |
        python manage.py check
    - name: Test
      run: |
        python manage.py test
